version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile.develop
    container_name: exhibition-dev
    env_file: .env
    network_mode: "host"
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    command: /bin/bash -c 'bun i &&  bun run build:packages  && bun run dev:exhibition'
